[package]
name = "pear_codegen"
version = "0.1.0"
authors = ["Sergio Benitez <sb@sergio.bz>"]
description = "A (codegen) pear is a fruit."
license = "MIT/Apache-2.0"

[lib]
proc-macro = true

[dependencies]
quote = "*"
proc-macro2 = { version = "*", features = ["nightly"] }
syn = { version = "0.13.2", features = ["full", "extra-traits", "visit-mut"] }

[build-dependencies]
yansi = "0.4"
version_check = "0.1.3"
