[package]
name = "pear_codegen"
version = "0.0.16"
authors = ["Sergio Benitez <sb@sergio.bz>"]
description = "A (codegen) pear is a fruit."
license = "MIT/Apache-2.0"

[lib]
plugin = true

[build-dependencies]
yansi = "0.4"
version_check = "0.1.3"
